#!/usr/bin/env bash
# Generate the hermes-agent-z4gq compose = the original Hostinger services
# (base/hermes-base.yml) + one service per Pantheon agent. This puts every
# agent in the SAME group as the existing hermes-agent (project
# "hermes-agent-z4gq"), not a separate stack. Each agent still bind-mounts its
# own isolated brain at /root/Pantheon/agents/<name>/data.
# Re-run after adding or removing an agent.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")" && pwd)"
BASE="${PANTHEON_BASE:-$ROOT/base/hermes-base.yml}"
OUT="${PANTHEON_COMPOSE_OUT:-/docker/hermes-agent-z4gq/docker-compose.yml}"
IMG="ghcr.io/hostinger/hvps-hermes-agent:latest"

[ -f "$BASE" ] || { echo "base missing: $BASE (pristine Hostinger compose)"; exit 1; }

{
  echo "# GENERATED by /root/Pantheon/gen-compose.sh — base + one service per agent. Do not hand-edit."
  echo "name: hermes-agent-z4gq"   # pin the project so the group is stable regardless of cwd
  cat "$BASE"
  echo ""
  echo "  # ─── Pantheon fleet — generated by /root/Pantheon/gen-compose.sh ───"
  n=0
  for d in "$ROOT"/agents/*/; do
    [ -d "${d}data" ] || continue
    a="$(basename "$d")"; n=$((n+1))
    cat <<SVC
  ${a}:
    image: ${IMG}
    container_name: hermes-${a}
    restart: unless-stopped
    env_file:
      - ${ROOT}/shared.env
    volumes:
      - ${ROOT}/agents/${a}/data:/opt/data
    ports:
      - "4860"
    networks:
      - default
      - kea-prod_default
SVC
  done
  echo "# pantheon agents: ${n}"
  echo ""
  echo "networks:"
  echo "  kea-prod_default:"
  echo "    external: true   # the local SearXNG (kea-prod-searxng-1) lives here"
} > "$OUT"
echo "wrote $OUT (base + ${n:-0} agents) — all under project 'hermes-agent-z4gq'"
