#!/usr/bin/env bash
# Generate ONE docker-compose.yml for the whole fleet: project "pantheon" with
# one service per agent dir under agents/. This makes the fleet a SINGLE group/
# stack in Docker (Portainer/Dockge/Hostinger), not ten separate ones. Each
# service still bind-mounts its own isolated brain at agents/<name>/data.
# Re-run after adding or removing an agent.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")" && pwd)"
OUT="$ROOT/docker-compose.yml"
IMG="ghcr.io/hostinger/hvps-hermes-agent:latest"

{
  echo "# GENERATED by gen-compose.sh — do not hand-edit; re-run after adding/removing an agent."
  echo "name: pantheon"
  echo "services:"
  n=0
  for d in "$ROOT"/agents/*/; do
    [ -d "${d}data" ] || continue
    a="$(basename "$d")"
    n=$((n+1))
    cat <<SVC
  ${a}:
    image: ${IMG}
    container_name: pantheon-${a}
    restart: unless-stopped
    env_file:
      - ./shared.env            # ttyd admin login (gateway reads keys+telegram from ./agents/${a}/data/.env)
    volumes:
      - ./agents/${a}/data:/opt/data
    ports:
      - "4860"                  # ttyd admin terminal, random host port; Telegram needs no inbound port
SVC
  done
} > "$OUT"
echo "wrote $OUT — project 'pantheon' with ${n:-0} service(s)"
